services:
  kali:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kali
    ports:
      - "8080:80"
      - "2222:22"
    stdin_open: true # equivalent to -i
    tty: true # equivalent to -t
    restart: always # optional, if you want the container to restart automatically
    networks:
      - laboratory-kali

networks:
  laboratory-kali:
    driver: bridge